"""
Death Circuit - Game Configuration
Contains all constants, colors, and game parameters
"""

import pygame

# Screen and Display
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60
TILE_SIZE = 32
GRID_WIDTH = SCREEN_WIDTH // TILE_SIZE
GRID_HEIGHT = SCREEN_HEIGHT // TILE_SIZE

# Colors (RGB)
BACKGROUND_COLOR = (10, 10, 10)
GRID_COLOR = (26, 26, 46)
PLAYER_COLOR = (0, 255, 255)
ENEMY_RUSHER_COLOR = (255, 68, 68)
ENEMY_SNIPER_COLOR = (255, 170, 0)
ENEMY_DODGER_COLOR = (170, 0, 255)
ENEMY_FLANKER_COLOR = (0, 255, 136)
BULLET_COLOR = (255, 255, 255)
WALL_COLOR = (51, 68, 85)
UI_TEXT_COLOR = (255, 255, 255)
UI_SHADOW_COLOR = (0, 0, 0)
HEALTH_BAR_BG = (50, 50, 50)
AMMO_BAR_BG = (50, 50, 50)

# Player Settings
PLAYER_SIZE = 24
PLAYER_SPEED = 200  # pixels per second
PLAYER_MAX_HEALTH = 100
PLAYER_REGEN_DELAY = 5.0  # seconds
PLAYER_REGEN_RATE = 10  # health per second
PLAYER_INVINCIBILITY_DURATION = 0.1  # seconds

# Enemy Settings
ENEMY_BASE_HEALTH = 40
ENEMY_HEALTH_SCALING = 0.1  # 10% increase per wave
ENEMY_MAX_HEALTH_BONUS = 1.0  # 100% max bonus
ENEMY_BASE_ACCURACY = 0.7
ENEMY_ACCURACY_SCALING = 0.05  # 5% increase per wave
ENEMY_MAX_ACCURACY = 0.95
ENEMY_SPAWN_INVINCIBILITY = 1.0  # seconds

# AI Behavior Parameters
AI_UPDATE_RATE = 6  # frames (10 FPS)
RUSHER_SPEED = 150
RUSHER_ATTACK_RANGE = 200
SNIPER_SPEED = 100
SNIPER_PREFERRED_RANGE = 400
SNIPER_RETREAT_RANGE = 300
SNIPER_SHOT_PREPARE_TIME = 1.0
DODGER_SPEED = 120
DODGER_DASH_SPEED = 250
DODGER_DASH_DURATION = 0.3
DODGER_DASH_COOLDOWN = 2.0
DODGER_BULLET_DODGE_RADIUS = 100
FLANKER_SPEED = 130
FLANKER_FLANK_ANGLE = 90  # degrees
FLANKER_RETREAT_DISTANCE = 200

# Weapon Settings
WEAPON_SWITCH_TIME = 0.0  # instant
PISTOL_DAMAGE = 20
PISTOL_FIRE_RATE = 3.0  # shots per second
PISTOL_BULLET_SPEED = 500
PISTOL_SPREAD = 0.05  # radians
PISTOL_MAGAZINE_SIZE = 12
PISTOL_RELOAD_TIME = 1.5

SMG_DAMAGE = 10
SMG_FIRE_RATE = 10.0
SMG_BULLET_SPEED = 600
SMG_SPREAD = 0.1
SMG_MAGAZINE_SIZE = 30
SMG_RELOAD_TIME = 2.0

SHOTGUN_DAMAGE = 8
SHOTGUN_PELLETS = 8
SHOTGUN_FIRE_RATE = 1.0
SHOTGUN_BULLET_SPEED = 400
SHOTGUN_SPREAD = 0.3
SHOTGUN_MAGAZINE_SIZE = 6
SHOTGUN_RELOAD_TIME = 2.5

RIFLE_DAMAGE = 35
RIFLE_FIRE_RATE = 1.5
RIFLE_BULLET_SPEED = 800
RIFLE_SPREAD = 0.02
RIFLE_MAGAZINE_SIZE = 10
RIFLE_RELOAD_TIME = 2.0

# Bullet Settings
BULLET_SIZE = 4
BULLET_LIFETIME = 3.0  # seconds
BULLET_TRAIL_LENGTH = 5
BULLET_TRAIL_DURATION = 0.2

# Map Generation
WALL_COUNT_MIN = 5
WALL_COUNT_MAX = 10
WALL_MIN_WIDTH = 2  # tiles
WALL_MAX_WIDTH = 8  # tiles
WALL_MIN_HEIGHT = 1  # tiles
WALL_MAX_HEIGHT = 3  # tiles
WALL_CLEARANCE_CENTER = 200  # pixels
WALL_CLEARANCE_EDGES = 50  # pixels

# Wave System
WAVE_BREAK_TIME = 5.0  # seconds
WAVE_BASE_ENEMIES = 3
WAVE_ENEMY_INCREMENT = 2
BOSS_WAVE_INTERVAL = 5
BOSS_HEALTH_MULTIPLIER = 2.0

# Particle System
PARTICLE_MAX_COUNT = 500
MUZZLE_FLASH_PARTICLES = 8
MUZZLE_FLASH_LIFETIME = 0.1
BLOOD_PARTICLES = 15
BLOOD_LIFETIME = 0.5
DEATH_EXPLOSION_PARTICLES = 40
DEATH_EXPLOSION_LIFETIME = 1.0
IMPACT_SPARKS = 5
IMPACT_LIFETIME = 0.2

# UI Settings
UI_FONT_SIZE_SMALL = 16
UI_FONT_SIZE_MEDIUM = 24
UI_FONT_SIZE_LARGE = 32
CROSSHAIR_SIZE = 20
HEALTH_BAR_WIDTH = 200
HEALTH_BAR_HEIGHT = 20
AMMO_BAR_WIDTH = 150
AMMO_BAR_HEIGHT = 15
SCREEN_SHAKE_INTENSITY = 2
SCREEN_SHAKE_DURATION = 0.2

# Collision
COLLISION_EPSILON = 0.1
ENTITY_SPACING = 50  # minimum distance between enemies

# Game States
STATE_MENU = 0
STATE_PLAYING = 1
STATE_PAUSED = 2
STATE_GAME_OVER = 3

# Controls
KEY_UP = pygame.K_w
KEY_DOWN = pygame.K_s
KEY_LEFT = pygame.K_a
KEY_RIGHT = pygame.K_d
KEY_RELOAD = pygame.K_r
KEY_PAUSE = pygame.K_ESCAPE
KEY_WEAPON_1 = pygame.K_1
KEY_WEAPON_2 = pygame.K_2
KEY_WEAPON_3 = pygame.K_3
KEY_WEAPON_4 = pygame.K_4

# Mouse
MOUSE_LEFT = 1
MOUSE_RIGHT = 3